# MODO DE DESENVOLVIMENTO
# Constrói imagens localmente e usa hot-reload
# Roda na porta 8000

services:
  # TRAEFIK
  traefik:
    image: "traefik:v2.11"  # Voltando para a versão "tanque de guerra"
    container_name: "traefik_proxy_legacy" # Nome novo para garantir recriação
    restart: always
    environment:
      # Mantemos a variável, a v2 costuma respeitar melhor
      - DOCKER_API_VERSION=1.44
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy-net
    # Adicionamos isto para tentar furar bloqueios de segurança (AppArmor/SELinux)
    security_opt:
      - "label:disable"

  # APLICAÇÃO DE NOTÍCIAS (FLASK)
  news-service:
    build: ./news_service #constrói uma imagem nova do zero a partir do dockerfile contido na pasta ./news_service
    container_name: news_flask_service
    restart: always #se o container parar, o docker reinicializa automaticamente
    # O 'command' está no Dockerfile (Gunicorn)
    volumes:
      - ./news_service:/app #mapeia a pasta do codigo-fonte para dentro da pasta /app dentro do container. Possibilita o "hot-reload" --> reinicia o container quando vê uma mudança no código.
      - news_media_volume:/app/app/static/uploads #mapeia um volume para a pasta de uploads (guarda os arquivos mesmo que reinicie o container)
    expose:
      - 8000 #expõe a porta internamente, apenas para os serviços na mesma rede. 
    environment:
      # Variáveis Banco de Dados 
      - MYSQL_DATABASE=${NEWS_DB_DATABASE}
      - MYSQL_USER=${NEWS_DB_USER}
      - MYSQL_PASSWORD=${NEWS_DB_PASSWORD}
      - MYSQL_HOST=news-db #conecta ao host news-db (nome do serviço do banco de dados)
      # Variáveis Flask
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG} # <-- Lido do .env
      - SECRET_KEY=${SECRET_KEY}
      # Variáveis Flask-Session (para conectar ao Redis)
      - SESSION_TYPE=${SESSION_TYPE}
      - SESSION_REDIS=${SESSION_REDIS_URL} #aponta para o serviço redis-sessions na porta 6379
    depends_on:
      #controla a ordem de inicialização 
      news-db:
        condition: service_healthy #só inicia o news_service quando o news-db estiver saudável (healthcheck).
      redis-sessions:
        condition: service_started #só inicia o news-service quando o redis tiver inicializado
    networks:
      - proxy-net #conecta o serviço à rede proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-net"
      
      # ROTA PRINCIPAL: Aceita /noticias, e entrega /noticias (sem cortar nada)
      - "traefik.http.routers.news-router.rule=PathPrefix(`/noticias`)"
      - "traefik.http.routers.news-router.entrypoints=web"
      # REMOVIDO: Middlewares de strip (não precisamos mais deles)
      
      # ROTA DE MÍDIA: Essa a gente MANTÉM o strip, porque a pasta no disco não chama "media"
      - "traefik.http.routers.news-media-router.rule=PathPrefix(`/media`)"
      - "traefik.http.routers.news-media-router.entrypoints=web"
      - "traefik.http.middlewares.media-strip.stripprefix.prefixes=/media"
      - "traefik.http.routers.news-media-router.middlewares=media-strip"

      - "traefik.http.services.news-service.loadbalancer.server.port=8000"

  # BANCO DE DADOS DO SERVIÇO NOTÍCIAS 
  news-db:
    image: mariadb:10.6
    container_name: noticias_mariadb
    restart: always #se o container parar, o docker reinicializa automaticamente
    environment:
      #variáveis de ambiente (lidas do .env)
      MYSQL_DATABASE: ${NEWS_DB_DATABASE}
      MYSQL_USER: ${NEWS_DB_USER}
      MYSQL_PASSWORD: ${NEWS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${NEWS_DB_ROOT_PASSWORD}
    volumes:
      - news_db_data:/var/lib/mysql #mapeia o volume nomeado news_db_data para a pasta interna do MariaDB (dados persistidos)
    healthcheck:
      #define como o docker deve verificar se o banco está saudável
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${NEWS_DB_USER}", "-p${NEWS_DB_PASSWORD}" ] #testes 
      interval: 10s #executa a verificação a cada 10 segundos
      timeout: 5s #falha se demorar mais que 5 segundos
      retries: 5 #tenta 5 vezes antes de marcar unealthy
    networks:
      - proxy-net #conecta o serviço à rede proxy-net

  # APLICAÇÃO DE USUÁRIOS (FLASK)
  users-service:
    #IGUAL O news-service SÓ MUDA AS VARIÁVEIS
    build: ./users_service #constrói uma imagem nova do zero a partir do dockerfile contido na pasta ./users_service
    container_name: users_flask_service
    restart: always #se o container parar, o docker reinicializa automaticamente
    # O 'command' está no Dockerfile
    volumes:
      - ./users_service:/app #mapeia a pasta do codigo-fonte para dentro da pasta /app dentro do container. Possibilita o "hot-reload" --> reinicia o container quando vê uma mudança no código.
    expose:
      - 8000 #expõe a porta internamente, apenas para os serviços na mesma rede. 
    environment:
      - MYSQL_DATABASE=${USERS_DB_DATABASE}
      - MYSQL_USER=${USERS_DB_USER}
      - MYSQL_PASSWORD=${USERS_DB_PASSWORD}
      - MYSQL_HOST=users-db #conecta ao serviço users-db
      # Variáveis do Flask
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG} # <-- Lido do .env
      - SECRET_KEY=${SECRET_KEY}
      # Variáveis do Flask-Session (para conectar ao Redis)
      - SESSION_TYPE=${SESSION_TYPE}
      - SESSION_REDIS=${SESSION_REDIS_URL} #aponta para o serviço redis-sessions na porta 6379
    depends_on:
      users-db:
        condition: service_healthy
      redis-sessions:
        condition: service_started
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-net"
      
      # ROTA DE CADASTRO: Aceita /cadastro e entrega /cadastro
      - "traefik.http.routers.users-router.rule=PathPrefix(`/cadastro`)"
      - "traefik.http.routers.users-router.entrypoints=web"
      # REMOVIDO: Middlewares de strip

      # IMPORTANTE: Você precisa de uma rota pro Traefik enxergar a API também!
      # Adicionei isso aqui para sua API interna funcionar:
      - "traefik.http.routers.users-api-router.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.users-api-router.entrypoints=web"
      
      - "traefik.http.services.users-service.loadbalancer.server.port=8000"

  # BANCO DE DADOS DE USUÁRIOS
  users-db:
    #IGUAL O news-db SÓ MUDA AS VARIÁVEIS
    image: mariadb:10.6
    container_name: users_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${USERS_DB_DATABASE}
      MYSQL_USER: ${USERS_DB_USER}
      MYSQL_PASSWORD: ${USERS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${USERS_DB_ROOT_PASSWORD}
    volumes:
      - users_db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${USERS_DB_USER}", "-p${USERS_DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - proxy-net

  # BANCO DE SESSÕES COMPARTILHADO
  redis-sessions:
    image: "redis:alpine"
    container_name: redis_sessions_db
    restart: always
    expose:
      - 6379 #expõe a porta padrão do redis 6379
    networks:
      - proxy-net

volumes:
  #decalra os volumes nomeados que utilizamos, Docker armazena eles em um local separado e os gerencia.
  news_db_data:
  news_media_volume:
  users_db_data:
  users_media_volume:
    # (não está sendo usado pq o users-service não contém uploads de arquivos estáticos)

networks:
  #definição da rede personalizada
  proxy-net:
    driver: bridge #tipo de rede (padrão bridge)
    name: proxy-net
    #todos os serviços conectados à essa rede podem se comunicar utilizando seus nomes de serviços como hostnames (Ex: news-service encontra o news-db no endereço http://news-db).