global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'news-service'
    static_configs:
      - targets: ['news-service:8000']

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:8000']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
